### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by LucianoPolit** [svdo/ReRxSwift#14]
New version should be released in order to start using SPM. I would suggest doing a `minor` bump to `2.3.0`.

**Comment by svdo** [comment]
Yes indeed, that also occurred to me while I was drinking my beer this evening 😀 Will do tomorrow!

**Comment by LucianoPolit** [comment]
Thanks a lot and enjoy that beer 💪

**Comment by svdo** [comment]
Done! Since _nothing_ else changed, I labeled the version `2.2.2`. Thanks again!
