### ISSUE TITLE
Can update to the least RxSwift?

### ISSUE THREAD

**Issue by Linyuyu** [svdo/ReRxSwift#17]
I like your idea and your project. Hoping It can be  maintained continuously.

I meet with some error in SPM fetching:

```
Showing All Messages
because ReRxSwift >=2.2.2 depends on RxSwift 5.0.0..<6.0.0 and root depends on RxSwift 6.1.0..<7.0.0, ReRxSwift >=2.2.2 is forbidden.
And because root depends on ReRxSwift 2.2.2..<3.0.0, version solving failed.
```

**Comment by svdo** [comment]
Thank you for your kind words! I'll see if I can update things soon. If you would like to try making a pull request, that's of course always welcome, but otherwise I'll be happy to do it myself soon.

**Comment by svdo** [comment]
@Linyuyu I have updated the dependencies. Is it ok for you now?
