### ISSUE TITLE
RxSwift 5 Support

### ISSUE THREAD

**Issue by 0zguner** [svdo/ReRxSwift#9]
https://github.com/svdo/ReRxSwift/pull/10

**Comment by svdo** [comment]
Merged. Thanks!!

**Comment by zakdances** [comment]
I'm still getting a `Conversion to Swift 5 is available` warning from XCode for ReRxSwift 2.2.0.

**Comment by svdo** [comment]
@zakdances How are you integrating it? Cocoapods? Carthage?

**Comment by svdo** [comment]
@zakdances I pushed a new release of ReRxSwift to CocoaPods, which I believe solves your "Conversion to Swift 5 is available" warning. Please note that this was unrelated to this issue, which was about **`RxSwift`**, not Swift itself.

**Comment by zakdances** [comment]
@svdo Thank you! Looks like no more warning.
